services:
  mysql:
    image: mysql:8.0
    container_name: beeyes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: beeyes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - beeyes-network

  redis:
    image: redis:7-alpine
    container_name: beeyes-redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - beeyes-network


  influxdb:
    image: influxdb:2.7
    container_name: beeyes-influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: beeyes
      DOCKER_INFLUXDB_INIT_BUCKET: beeyes-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: beeyes-token-123456789
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - beeyes-network

  kafka:
    image: bitnami/kafka:latest
    container_name: beeyes-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@beeyes-kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - beeyes-network


volumes:
  mysql_data:
  redis_data:
  kafka_data:
  influxdb_data:
  influxdb_config:

networks:
  beeyes-network:
    driver: bridge

