springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
server:
  compression:
    enabled: true

spring:
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
  influx-db:
    url: ${INFLUXDB_URL}
    token: ${INFLUXDB_TOKEN}
    bucket: ${INFLUXDB_BUCKET}
    org: ${INFLUXDB_ORG}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: latest
      max-poll-records: 100
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      password: ${REDIS_PASSWORD}
      timeout: 2000
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  web:
    flow:
      period: 3
      limit: 50
      block: 30

sa-token:
  token-name: jinyum
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: tik
  is-log: false

monitor:
  time: 5
