springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
server:
  compression:
    enabled: true

spring:
  mail:
    host: ""
    username: ""
    password: ""
  influx-db:
    url: http://localhost:8086
    token: "vCtq0Ih1b-n6RPR75bCP-_nTPXjKvxEcod_GPVMAkjOeN54JABbBqHfUKQy-WOcrBxOo7BLj7FxVPtl6Ua6g7w=="
    bucket: "BeEyes"
    org: "docs"
  datasource:
    url: jdbc:mysql://localhost:3306/be_eyes
    username: root
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 2000
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'

sa-token:
  token-name: jinyum
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: tik
  is-log: false